nginx:
    build: ./Dockerfiles/nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node1:
    build: ./Dockerfiles/nodejs
    links:
        - mongo
    ports:
        - "8080"
node2:
    build: ./Dockerfiles/nodejs
    links:
        - mongo
    ports:
        - "8080"
node3:
    build: ./Dockerfiles/nodejs
    links:
        - mongo
    ports:
        - "8080"
mongo:
    image: mongo:3.2.18
    ports:
        - "27017"

